### ISSUE TITLE
Alternative version that doesn't throw

### ISSUE THREAD

**Issue by joneshf** [mattbierner/bennu#23]
This library is great and fits the bill almost entirely, except for one thing. `run` and friends throw errors. How do you feel about another function that returns a data structure rather than throwing? It could be as simple as wrapping it in something like [fantasy-eithers](https://github.com/fantasyland/fantasy-eithers/blob/master/src/either.js), [data.either](http://docs.folktalejs.org/en/latest/api/data/either/index.html), something more complex like [data.validation](http://docs.folktalejs.org/en/latest/api/data/validation/index.html), or a custom data type. Any of these would be great. If you have a suggestion, I can throw a pr together.

**Comment by mattbierner** [comment]
Take a look at `parse`, `parseStream`, and `parseState`. These allow you to pass in custom success and error continuations that are invoked with the results.

`parse` is the most simple and takes an array-like object (`run` is actually implemented using `parse`). The signature is: `parse(parser, input, userData, okCallback, errorCallback)`:

```
parse(many1(character("a")), "aaaxu", null /* user data */,
    function(result) {
        return Either.Right(result);
    },
    function(err) {
      return Either.Left(err);
   });
```

The returned value of `parse` is the result of the continuation that is evaluated. 

Let me know if that is what you are looking for.

**Comment by joneshf** [comment]
Oh awesome! I had assumed they were asynchronous. But since `parse` isn't async, it looks like this will work. Thanks!
