### ISSUE TITLE
What does cok and eok stand form?

### ISSUE THREAD

**Issue by ccorcos** [mattbierner/bennu#24]
Just reading through the code and I don't quite understand what `cok` `eok` `cerr` and `eerr` stand for: https://github.com/mattbierner/bennu/blob/master/lib/parse.kep#L134-L137

**Comment by mattbierner** [comment]
Here a quick breakdown:

For a given set of input, a parser can either succeed or fail. That's the `ok` and `err` part of the continuations names. The `c` and `e` prefix stand for `consume` and `empty`, meaning that the parser consumed some input or did not consume any input respectively.

The complete set of continuations is therefore:

- `cok`— Parser succeeded and consumed some input. For example `parse.token(...)`
- `eok`— Parser succeeded but did not consume any input, such as `parse.always(...)`
- `cerr` — Parser failed after having consumed input. This would be something like `parse.bind(token(...), x => parse.never(...))`
- `eerr` — Parser failed without consuming any input: `parse.never(...)`

Hope that clears things up

**Comment by ccorcos** [comment]
thanks -- that's all i needed. if you don't mind though, i'm curious about Khepri. you've written some pretty awesome libraries, but i'm afraid many people are uncomfortable using them since they're in a foreign language. are you still writing code with Khepri?
